[package]
name = "anki_maker"
version = "0.5.7"
edition = "2021"

[dependencies]

diff = "0.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
clap = "4.4"
app = { path = "./app" }

[[bin]]
name = "cli"

[[bin]]
name = "gui"
path = "./src/bin/gui.rs"

[workspace]
members = ["app"]
