[package]
name = "anki_maker"
version = "0.5.8"
edition = "2021"

[dependencies]

diff = "0.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
clap = { version = "4.4", features = ["derive"] }
app = { path = "./app" }

[[bin]]
name = "ankimaker"
path = "./src/bin/cli.rs"

[[bin]]
name = "gui"
path = "./src/bin/gui.rs"

[workspace]
members = ["app"]
